[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/travel-feed"
  to = "/.netlify/functions/travel-feed"
  status = 200

[[redirects]]
  from = "/api/whats-new"
  to = "/.netlify/functions/whats-new"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
